### ISSUE TITLE
Improve skipped product INFO message

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/harvest#106]
## 💪 Motivation
...so that I can better understand why the product is being skipped.

## 📖 Additional Details

Right now the output message says something like:
```
2022-10-21 08:55:00,875 [INFO] Skipping product /PDS/data/anonymous/PDS/data/PDS4/LADEE/nms_bundle/document/nms_pds_sis.xml
```
which doesn't say anything about why the product was skipped.

## ⚙️ Engineering Details

- [ ] update online registry documentation to describe all the instances when a product is skipped
- [ ] update error message to say explicitly (and succinctly) why the product is being skipped

**Comment by alexdunnjpl** [comment]
@jordanpadams I've pushed the log message change in #109 

There wasn't an obvious place to put the documentation change - is it really necessary given a properly-descriptive log message (see below)?  Seems too-specific a detail for the "level" of the existing documentation.

`Skipping product  path/to/some_product.xml (LIDVID/LID is not in collection inventory or is already registered in Elasticsearch;`

**Comment by jordanpadams** [comment]
@alexdunnjpl no that should suffice. thanks!

**Comment by tloubrieu-jpl** [comment]
@gxtchen the main reason for harvest to skip a product is because it has already been loaded in the registry. You can test that by loading twice the same product. The message should be:
`Skipping product  path/to/some_product.xml (LIDVID/LID is not in collection inventory or is already registered in Elasticsearch;`

**Comment by gxtchen** [comment]
@tloubrieu-jpl I am running harvest 3.7.6, the the message hasn't changed.
gchen@johns-macbook-pro harvest102 % harvest -V
Harvest version: 3.7.6

[WARN] Skipping registered product urn:nasa:pds:uranus_occ_support:data:uranus_occultation_ring_fit_rfrench_20191221::1.0
[WARN] Skipping registered product urn:nasa:pds:lunar-crust-magnetic.field-map:data::1.1
[SUMMARY] Summary:
[SUMMARY] Skipped files: 2

**Comment by alexdunnjpl** [comment]
@gxtchen what log level are you running your test at?  The log in this issue is INFO.

**Comment by gxtchen** [comment]
@alexdunnjpl I was running with default level, which is INFO. I tried the other levels after seeing your message, but I still don't see the expected message.

**Comment by alexdunnjpl** [comment]
@tloubrieu-jpl @jordanpadams that said, [this logic seems kinda janky](https://github.com/NASA-PDS/harvest/blob/ac371ab2e701336cccb45454fc6ca31718352d09/src/main/java/gov/nasa/pds/harvest/dao/MetadataWriter.java#L71) and it probably deserves a rewrite.

Granted this is my 11pm-brain, but it seems to read 

```
if not overwrite-mode, and if everything's already registered, 
    log everything and exit
else (if overwrite-mode or there are any novel products requiring registration -> i.e. if writes are required)
    if novel-ids list is null or novelProducts contains lidvid
        then write item
    else (if lidvid in novel-ids list)
        then log and skip lidvid
```

those last four lines of logic almost seem back-to-front.

**Comment by alexdunnjpl** [comment]
@gxtchen based on what I'm seeing, this has to be one of

 - The version you're testing is out-of-date
 - You're testing scalable-harvest, rather than standalone-harvest
 - We've failed to release the changed code properly
 
 If it's neither of the first two, ping me and I'll chase up option 3 tomorrow.

**Comment by gxtchen** [comment]
@alexdunnjpl I am running harvest 3.7.6 with registry docker.

**Comment by alexdunnjpl** [comment]
@gxtchen could I trouble you to dump the harvest config you're using, and a url or other reference I can use to pull the content you're harvesting?

**Comment by alexdunnjpl** [comment]
Thanks @gxtchen , I'll take a look today

**Comment by alexdunnjpl** [comment]
@gxtchen sorry for the delay - I've investigated and it's due to #109 being an incomplete fix for #106.  I'm reopening this issue on that basis.

@jordanpadams @tloubrieu-jpl I don't know how it affects our release process or Gary's testing - we can re-tag or just exclude this ticket from this release as it's not a super-important one, but the partial fix will remain unless we revert #109 before tagging.

**Comment by alexdunnjpl** [comment]
@jordanpadams @tloubrieu-jpl let me know if you want me to look more closely at [the surrounding logic](https://github.com/NASA-PDS/harvest/issues/106#issuecomment-1524758952) - I imagine it has to work as intended or it wouldn't be there, but it's seems weird.

**Comment by jordanpadams** [comment]
@gxtchen you will need to test this with the SNAPSHOT version for the time being: https://github.com/NASA-PDS/harvest/releases/tag/v3.8.0-SNAPSHOT
