### ISSUE TITLE
As a developer, I want to know what version of Harvest was used to load a product

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/harvest#119]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

EN Developer

### 💪 Motivation

...so that I can more easily debug issues with metadata.

### Acceptance Criteria

**Given** a harvested product
**When I perform** a query of the product from either the registry or registry API
**Then I expect** to see the Harvest version returned in the `ops:Harvest_Info/ops:software_version` value.

### ⚙️ Engineering Details

- create new `ops:Harvest_Info/ops:software_version` field
- add current harvest version to that value

**Comment by al-niessner** [comment]
@alexdunnjpl @jordanpadams 

It looks like the current harvest information is added to documents prior to harvesting. I think @alexdunnjpl knows harvest way better than I do, but the documentation in registry, I mean why would it be co-located with harvest, states that the node name must be, as in mandatory, be in a document before harvesting. I did not see any reference to the date-time however. Still, searched harvest for "ops:Harvest_Info" which it would have to know if programatically adding it. Nothing shows up.

If harvest was injecting its own information already, then I would have been happy to add another item. However, this does not appear to be the case. I can do one of two things:
1. Keep wading further into the weeds
2. Wait for a suggestion that points me in the right direction (hint to @alexdunnjpl if he knows it off hand

Obviously I will keep strolling through the weeds until better direction comes along.

**Comment by al-niessner** [comment]
@alexdunnjpl @jordanpadams 

Aha! It seems to be in registry-common. Now which version of the many repo/maven versions would you like to be used?

**Comment by alexdunnjpl** [comment]
@al-niessner if that's a legitimate question rather than a comment on the absolute _state_ of things, 1.4.0, as far as I know.

Re the other stuff, I haven't touched harvest in ages - are you good now or do I need to dig in a little?

**Comment by jordanpadams** [comment]
@al-niessner @alexdunnjpl I think what is returned from `harvest --version` would be ideal?

@tloubrieu-jpl ☝️

**Comment by al-niessner** [comment]
@alexdunnjpl @jordanpadams @tloubrieu-jpl 

> if that's a legitimate question rather than a comment on the absolute state of things, 1.4.0, as far as I know.

Well, it is both actually. So harvest depends upon registry-common. I just confirmed that because the version for `harvest --version` comes from  HarvestCli.class.getPackage().getImplementationVersion(). However, there is nothing to prevent one from updating the registry-common without updating the harvest POM version which is at 3.8.0. registry-common is 1.4.0. Or the other way round which would probably more likely. However if both change the behavior that you want to track, then it makes it kind of hard. Maybe if you pinky promise not to deliver a new harvest version X with an updated version of registry-common then you could just run off the harvest version. Problem with pinky swears is that people forget they made them or why then ignore them. So, yes, the state also plays a role.
