### ISSUE TITLE
Update to use directory_path_name when trying to locate //Document_File/file_name

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/harvest#41]
**Is your feature request related to a problem? Please describe.**
Current implementation only looks for `//Document_File/file_name` in current directory. `//Document_File/file_name/directory_path_name` can be used to give a sub-directory to look for `file_name`.

**Comment by rchenatjpl** [comment]
The following is not the behavior I expected, but is it correct or insignificant? hvt41a.xml is good; hvt41b.xml, bad due to missing directory_path_name. If I:
- harvest hvt41a.xml
- registry-manager load-data
- harvest hvt41b.xml
- registry-manager load-data
http://localhost:9200/registry/_search?q=* shows 1 hit, which is what I'd expect. Now, if I:
- harvest hvt41a.xml
- harvest hvt41b.xml
- registry-manager load-data
http://localhost:9200/registry/_search?q=* shows 0 hits, and /tmp/harvest/out/*.json have 0 bytes. I don't expect that since the two labels have different LIDs.
[Archive.zip](https://github.com/NASA-PDS/harvest/files/6530790/Archive.zip)

**Comment by tloubrieu-jpl** [comment]
@tdddblog can you reproduce the behavior Richard is experiencing ?

thanks

**Comment by tdddblog** [comment]
Works as designed. If you skip step 2, there will be no data in registry. If I understood correctly, step 3 doesn't produce any data either, so step 4 doesn't matter.
