### ISSUE TITLE
Error "Missing ids" does not provide enough information for debugging

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/harvest#96]
## 🐛 Describe the bug

Identified by ATM:
```
[SUMMARY] Output format: json 
[SUMMARY] Reading configuration from /home/itrejo/jnogrv_1001.cfg
[SUMMARY] Elasticsearch URL: https://search-atm-prod-mkvgzojag2ta65bnotqdpopzju.us-west-2.es.amazonaws.com:443, index: registry
[INFO] Reading registry schema from Elasticsearch
[INFO] Processing bundle directory /PDS/data/anonymous/PDS/data/jnogrv_1001
[INFO] Processing bundle /PDS/data/anonymous/PDS/data/jnogrv_1001/bundle_juno_grav.xml
[INFO] Processing collection /PDS/data/anonymous/PDS/data/jnogrv_1001/DOCUMENT/collection_document.xml
[ERROR] Missing ids
```

## 🕵️ Expected behavior

Error message includes much more useful information

## 📚 Version of Software Used

v3.6.0

## 🩺 Test Data / Additional context

TBD download from ATM

---

## ⚙️ Engineering Details
Looks like issue is here: https://github.com/NASA-PDS/harvest/blob/main/src/main/java/gov/nasa/pds/harvest/dao/EsRequestBuilder.java#L58 

For whatever reason, the software is unable to read the LIDs from the collection inventory.

Tightly coupled with https://github.com/NASA-PDS/harvest/issues/97

**Comment by ramesh-maddegoda** [comment]
@jordanpadams, I am wondering if they are using an older version of the harvest.

Because in the latest source code of harvest,

1) The [createSearchIdsRequest(Collection<String> ids, int pageSize) ](https://github.com/NASA-PDS/harvest/blob/main/src/main/java/gov/nasa/pds/harvest/dao/EsRequestBuilder.java#L58) is called by  [searchIds(Collection<String> ids)](https://github.com/NASA-PDS/harvest/blob/73833d62f5810a441aaf70eab055cda57fb9cec0/src/main/java/gov/nasa/pds/harvest/dao/RegistryDao.java#L96)

2) The [searchIds(Collection<String> ids)](https://github.com/NASA-PDS/harvest/blob/73833d62f5810a441aaf70eab055cda57fb9cec0/src/main/java/gov/nasa/pds/harvest/dao/RegistryDao.java#L96) is called by [getNonExistingIds(Collection<String> ids)](https://github.com/NASA-PDS/harvest/blob/73833d62f5810a441aaf70eab055cda57fb9cec0/src/main/java/gov/nasa/pds/harvest/dao/RegistryDao.java#L85)

3) In [getNonExistingIds(Collection<String> ids)](https://github.com/NASA-PDS/harvest/blob/73833d62f5810a441aaf70eab055cda57fb9cec0/src/main/java/gov/nasa/pds/harvest/dao/RegistryDao.java#L85), there is a check for null and empty IDs and it should not call searchIds(ids), if the IDs are missing.

```
 public Set<String> getNonExistingIds(Collection<String> ids) throws Exception
    {
        if(ids == null || ids.isEmpty()) return null;
        Response resp = searchIds(ids);
```

I think in the latest code, this Exception("Missing ids") cannot be thrown, when the IDs are empty or null.

**Comment by jordanpadams** [comment]
@ramesh-maddegoda copy thanks. Waiting onto he version info to come back from Irma. Stand by.

Thanks for looking into this!

**Comment by jordanpadams** [comment]
@ramesh-maddegoda making that change sounds good to me.

**Comment by jordanpadams** [comment]
@ramesh-maddegoda and maybe we can update that error message to say something like "Error reading bundle/collection references. Verify the bundle is valid prior to loading the data." or something like that?

**Comment by ramesh-maddegoda** [comment]
Created pull request https://github.com/NASA-PDS/harvest/pull/99 with the changes proposed above.

**Comment by jordanpadams** [comment]
Closed per https://github.com/NASA-PDS/harvest/pull/99

**Comment by tloubrieu-jpl** [comment]
@gxtchen this need to be tested from the latest snapshot version https://github.com/NASA-PDS/harvest/releases/tag/v3.7.0-SNAPSHOT

**Comment by gxtchen** [comment]
@jimmie Can you show me how to reproduce this issue? thx.

**Comment by jimmie** [comment]
@ramesh-maddegoda - do you have a test case for this or access to the originally failing ATM dataset?

**Comment by ramesh-maddegoda** [comment]
@jimmie and @gxtchen, There was another issue related to this https://github.com/NASA-PDS/harvest/issues/97#issuecomment-1184912455 

We found that user was using an older version harvest.

@jordanpadams, verified this with the user and closed the issue as follows.

`user verified they were using 3.6.0-SNAPSHOT, and once they upgraded to 3.6.0 this issue was fixed`

This issue should be also closed with https://github.com/NASA-PDS/harvest/issues/97#issuecomment-1184912455

**Comment by ramesh-maddegoda** [comment]
@jimmie and @gxtchen , the data set they had this issue was https://atmos.nmsu.edu/PDS/data/jnogrv_1001/DOCUMENT/

**Comment by jordanpadams** [comment]
thanks @ramesh-maddegoda. agreed.

**Comment by jordanpadams** [comment]
added `invalid` label to ticket so this can be avoided in the future
